name: Upload to Google Cloud Storage

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow on

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-storage
        
    - name: Execute Python script
      run: |
        cd Statefile-upload
        python main.py
      env:
        GCP_CREDS: ${{ secrets.GCP_CREDS }}
