name: Manual File Upload

on:
  workflow_dispatch:
    inputs:
      file-path:
        description: 'Path to the file to be uploaded'
        required: true

jobs:
  upload-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload File
        run: |
          mkdir -p Statefile-upload
          mv ${{ github.event.inputs.file-path }} State-file-upload
          git add path/to/uploaded/folder/${{ github.event.inputs.file-path }}
          git config --global user.email "rajat11299@gmail.com"
          git config --global user.name "rajat11299"
          git commit -m "Uploaded file"
          git push
